const types = {
    REGISTER_USER: 'REGISTER_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    MODIFY_USER: 'MODIFY_USER',
    USER_LOGINED: 'USER_LOGINED',
    GET_CURR_POST_NUM: 'GET_CURR_POST_NUM',
    REGISTER_POST: 'REGISTER_POST',
    EDIT_POST: 'EDIT_POST',
    GET_ALL_POSTS: 'GET_ALL_POSTS',
    GET_CURRENT_POSTS_NUM_INFO: 'GET_CURRENT_POSTS_NUM_INFO',
    UPDATE_POST_NUM: 'UPDATE_POST_NUM',
    LIKE: 'LIKE',
    UNLIKE: 'UNLIKE',
    GET_LIKED_POSTS: 'GET_LIKED_POSTS',
    DELETE_CHECKED_POSTS: 'DELETE_CHECKED_POSTS',
  };
  
  export default types;
  