const types = {
    REGISTER_USER: 'REGISTER_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    MODIFY_USER: 'MODIFY_USER',
    USER_LOGINED: 'USER_LOGINED',
    GET_CURR_POST_NUM: 'GET_CURR_POST_NUM',
    REGISTER_POST: 'REGISTER_POST',
    EDIT_POST: 'EDIT_POST',
    GET_ALL_POSTS: 'GET_ALL_POSTS',
    UPDATE_POST_NUM: 'UPDATE_POST_NUM',
    GET_MY_POSTS: 'GET_MY_POSTS',
    GET_MY_LIKED_POSTS: 'GET_MY_LIKED_POSTS',
    GET_PAGINATION_INFO: 'GET_PAGINATION_INFO',
    SET_POST_PER_PAGE: 'SET_POST_PER_PAGE',
  };
  
  export default types;
  